import tkinter as tk
from tkinter import ttk


window = tk.Tk()

window.winfo_reqwidth()
window.bind('<Escape>',lambda e: window.destroy())

window.geometry("1400x600")
lettres = ["a","b","c","d","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
numbers10 = [1,2,3,4,5,6,7,8,9,10]
numbers26 = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]

spbox1 = ttk.Combobox(window,values=lettres)
spbox2 = ttk.Combobox(window,values=lettres)
spbox3 = ttk.Combobox(window,values=lettres)
spbox4 = ttk.Combobox(window,values=lettres)
spbox5 = ttk.Combobox(window,values=lettres)
spbox6 = ttk.Combobox(window,values=lettres)
spbox7 = ttk.Combobox(window,values=lettres)
spbox8 = ttk.Combobox(window,values=lettres)
spbox9 = ttk.Combobox(window,values=lettres)
spbox10 = ttk.Combobox(window,values=lettres)

entry1 = tk.Entry(window)
entry2 = tk.Entry(window)
entry3 = tk.Entry(window)
entry4 = tk.Entry(window)
entry5 = tk.Entry(window)
entry6 = tk.Entry(window)
entry7 = tk.Entry(window)
entry8 = tk.Entry(window)
entry9 = tk.Entry(window)
entry10 = tk.Entry(window)


def LetterPos():
    numletword = example.get()
    numletword = int(numletword)
    if numletword in numbers10 :
        
        if numletword == 1 :
            spbox1.place(x=0,y= 50)
            spbox2.place_forget()
            spbox3.place_forget()
            spbox4.place_forget()
            spbox5.place_forget()
            spbox6.place_forget()
            spbox7.place_forget()
            spbox8.place_forget()
            spbox9.place_forget()
            spbox10.place_forget()
            
            entry1.place(x=0,y=100)
            entry2.place_forget()
            entry3.place_forget()
            entry4.place_forget()
            entry5.place_forget()
            entry6.place_forget()
            entry7.place_forget()
            entry8.place_forget()
            entry9.place_forget()
            entry10.place_forget()
            
        elif numletword == 2 :
            spbox1.place(x=0,y= 50)
            spbox2.place(x=150,y= 50)
            spbox3.place_forget()
            spbox4.place_forget()
            spbox5.place_forget()
            spbox6.place_forget()
            spbox7.place_forget()
            spbox8.place_forget()
            spbox9.place_forget()
            spbox10.place_forget()
            
            entry1.place(x=7,y= 100)
            entry2.place(x=157,y= 100)
            entry3.place_forget()
            entry4.place_forget()
            entry5.place_forget()
            entry6.place_forget()
            entry7.place_forget()
            entry8.place_forget()
            entry9.place_forget()
            entry10.place_forget()
        elif numletword == 3 :
            spbox1.place(x=0,y= 50)
            spbox2.place(x=150,y= 50)
            spbox3.place(x=300,y= 50)
            spbox4.place_forget()
            spbox5.place_forget()
            spbox6.place_forget()
            spbox7.place_forget()
            spbox8.place_forget()
            spbox9.place_forget()
            spbox10.place_forget()
            
            entry1.place(x=7,y= 100)
            entry2.place(x=157,y= 100)
            entry3.place(x=307,y= 100)
            entry4.place_forget()
            entry5.place_forget()
            entry6.place_forget()
            entry7.place_forget()
            entry8.place_forget()
            entry9.place_forget()
            entry10.place_forget()
        elif numletword == 4 :
            spbox1.place(x=0,y= 50)
            spbox2.place(x=150,y= 50)
            spbox3.place(x=300,y= 50)
            spbox4.place(x=450,y= 50)
            spbox5.place_forget()
            spbox6.place_forget()
            spbox7.place_forget()
            spbox8.place_forget()
            spbox9.place_forget()
            spbox10.place_forget()
            
            entry1.place(x=7,y= 100)
            entry2.place(x=157,y= 100)
            entry3.place(x=307,y= 100)
            entry4.place(x=457,y= 100)
            entry5.place_forget()
            entry6.place_forget()
            entry7.place_forget()
            entry8.place_forget()
            entry9.place_forget()
            entry10.place_forget()
            
        elif numletword == 5 :
            spbox1.place(x=0,y= 50)
            spbox2.place(x=150,y= 50)
            spbox3.place(x=300,y= 50)
            spbox4.place(x=450,y= 50)
            spbox5.place(x=600,y= 50)
            spbox6.place_forget()
            spbox7.place_forget()
            spbox8.place_forget()
            spbox9.place_forget()
            spbox10.place_forget()
            
            entry1.place(x=7,y= 100)
            entry2.place(x=157,y= 100)
            entry3.place(x=307,y= 100)
            entry4.place(x=457,y= 100)
            entry5.place(x=607,y= 100)
            entry6.place_forget()
            entry7.place_forget()
            entry8.place_forget()
            entry9.place_forget()
            entry10.place_forget()
        elif numletword == 6 :
            spbox1.place(x=0,y= 50)
            spbox2.place(x=150,y= 50)
            spbox3.place(x=300,y= 50)
            spbox4.place(x=450,y= 50)
            spbox5.place(x=600,y= 50)
            spbox6.place(x=750,y= 50)
            spbox7.place_forget()
            spbox8.place_forget()
            spbox9.place_forget()
            spbox10.place_forget()
            
            entry1.place(x=7,y= 100)
            entry2.place(x=157,y= 100)
            entry3.place(x=307,y= 100)
            entry4.place(x=457,y= 100)
            entry5.place(x=607,y= 100)
            entry6.place(x=757,y= 100)
            entry7.place_forget()
            entry8.place_forget()
            entry9.place_forget()
            entry10.place_forget()
        elif numletword == 7:
            spbox1.place(x=0,y= 50)
            spbox2.place(x=150,y= 50)
            spbox3.place(x=300,y= 50)
            spbox4.place(x=450,y= 50)
            spbox5.place(x=600,y= 50)
            spbox6.place(x=750,y= 50)
            spbox7.place(x=900,y= 50)
            spbox8.place_forget()
            spbox9.place_forget()
            spbox10.place_forget()
            
            entry1.place(x=7,y= 100)
            entry2.place(x=157,y= 100)
            entry3.place(x=307,y= 100)
            entry4.place(x=457,y= 100)
            entry5.place(x=607,y= 100)
            entry6.place(x=757,y= 100)
            entry7.place(x=907,y= 100)
            entry8.place_forget()
            entry9.place_forget()
            entry10.place_forget()
        elif numletword == 8 :
            spbox1.place(x=0,y= 50)
            spbox2.place(x=150,y= 50)
            spbox3.place(x=300,y= 50)
            spbox4.place(x=450,y= 50)
            spbox5.place(x=600,y= 50)
            spbox6.place(x=750,y= 50)
            spbox7.place(x=900,y= 50)
            spbox8.place(x=1050,y= 50)
            spbox9.place_forget()
            spbox10.place_forget()
            
            entry1.place(x=7,y= 100)
            entry2.place(x=157,y= 100)
            entry3.place(x=307,y= 100)
            entry4.place(x=457,y= 100)
            entry5.place(x=607,y= 100)
            entry6.place(x=757,y= 100)
            entry7.place(x=907,y= 100)
            entry8.place(x=1057,y= 100)
            entry9.place_forget()
            entry10.place_forget()
        elif numletword == 9 :
            spbox1.place(x=0,y= 50)
            spbox2.place(x=150,y= 50)
            spbox3.place(x=300,y= 50)
            spbox4.place(x=450,y= 50)
            spbox5.place(x=600,y= 50)
            spbox6.place(x=750,y= 50)
            spbox7.place(x=900,y= 50)
            spbox8.place(x=1050,y= 50)
            spbox9.place(x=1200,y= 50)
            spbox10.place_forget()
            
            entry1.place(x=7,y= 100)
            entry2.place(x=157,y= 100)
            entry3.place(x=307,y= 100)
            entry4.place(x=457,y= 100)
            entry5.place(x=607,y= 100)
            entry6.place(x=757,y= 100)
            entry7.place(x=907,y= 100)
            entry8.place(x=1057,y= 100)
            entry9.place(x=1207,y= 100)
            entry10.place_forget()
        elif numletword == 10 :
            spbox1.place(x=0,y= 50)
            spbox2.place(x=150,y= 50)
            spbox3.place(x=300,y= 50)
            spbox4.place(x=450,y= 50)
            spbox5.place(x=600,y= 50)
            spbox6.place(x=750,y= 50)
            spbox7.place(x=900,y= 50)
            spbox8.place(x=1050,y= 50)
            spbox9.place(x=1200,y= 50)
            spbox10.place(x=1350,y= 50)
            
            entry1.place(x=7,y= 100)
            entry2.place(x=157,y= 100)
            entry3.place(x=307,y= 100)
            entry4.place(x=457,y= 100)
            entry5.place(x=607,y= 100)
            entry6.place(x=757,y= 100)
            entry7.place(x=907,y= 100)
            entry8.place(x=1057,y= 100)
            entry9.place(x=1207,y= 100)
            entry10.place(x=1357,y= 100)

def toggle():
    print(toggle_btn.config('relief')[-1])
    if toggle_btn.config('relief')[-1] == 'sunken':
        toggle_btn.config(relief="raised")
    else:
        toggle_btn.config(relief="sunken")
            
def test():
    print("ca marche")

tk.Label(window,text="Nombre de lettre du mot :").place(x = 0,y= 5)

example = ttk.Combobox(window,values=numbers10)
example.place(x=150,y=5)

tk.Button(window,text="OK",command=LetterPos).place(x=300,y=2)

tk.Label(window,text="Entrer les bonnes lettres :").place(x = 0, y = 25)

tk.Label(window,text="Entrer les lettres mal placés aux endroits où on sais qu'elle ne peuvent pas être :").place(x=0,y=75)

tk.Label(window,text="Selectionner les lettres impossibles :").place(x=0,y=125)

toggle_btn = tk.Button(window,text="Toggle", width=12, relief="raised")
toggle_btn.place(x=20,y=150)

tk.Button(window,text="A",command=test).place(x=0,y=175)
# tk.Button(window,text="Z").grid(row = 7,column = 1,padx = 50,pady = 20)
# tk.Button(window,text="E").grid(row = 7,column = 2,padx = 50,pady = 20)
# tk.Button(window,text="R").grid(row = 7,column = 3,padx = 50,pady = 20)
# tk.Button(window,text="T").grid(row = 7,column = 4,padx = 50,pady = 20)
# tk.Button(window,text="Y").grid(row = 7,column = 5,padx = 50,pady = 20)
# tk.Button(window,text="U").grid(row = 7,column = 6,padx = 50,pady = 20)
# tk.Button(window,text="I").grid(row = 7,column = 7,padx = 50,pady = 20)
# tk.Button(window,text="O").grid(row = 7,column = 8,padx = 50,pady = 20)
# tk.Button(window,text="P").grid(row = 7,column = 9,padx = 50,pady = 20)

# tk.Button(window,text="Q").grid(row = 8,column = 0,padx = 50,pady = 20)
# tk.Button(window,text="S").grid(row = 8,column = 1,padx = 50,pady = 20)
# tk.Button(window,text="D").grid(row = 8,column = 2,padx = 50,pady = 20)
# tk.Button(window,text="F").grid(row = 8,column = 3,padx = 50,pady = 20)
# tk.Button(window,text="G").grid(row = 8,column = 4,padx = 50,pady = 20)
# tk.Button(window,text="H").grid(row = 8,column = 5,padx = 50,pady = 20)
# tk.Button(window,text="J").grid(row = 8,column = 6,padx = 50,pady = 20)
# tk.Button(window,text="K").grid(row = 8,column = 7,padx = 50,pady = 20)
# tk.Button(window,text="L").grid(row = 8,column = 8,padx = 50,pady = 20)
# tk.Button(window,text="M").grid(row = 8,column = 9,padx = 50,pady = 20)

# tk.Button(window,text="W").grid(row = 9,column = 1,padx = 50,pady = 20)
# tk.Button(window,text="X").grid(row = 9,column = 2,padx = 50,pady = 20)
# tk.Button(window,text="C").grid(row = 9,column = 3,padx = 50,pady = 20)
# tk.Button(window,text="V").grid(row = 9,column = 4,padx = 50,pady = 20)
# tk.Button(window,text="B").grid(row = 9,column = 5,padx = 50,pady = 20)
# tk.Button(window,text="N").grid(row = 9,column = 6,padx = 50,pady = 20)

window.mainloop()